# Generated by Django 2.0.6 on 2018-07-04 21:40

from django.db import migrations, models
import django_assets.assets.models.asset


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ManyToManyField(blank=True, to='assets.Category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.CharField(choices=[(django_assets.assets.models.asset.AssetStates('En réparation'), 'En réparation'), (django_assets.assets.models.asset.AssetStates("En cours d'utilisation"), "En cours d'utilisation"), (django_assets.assets.models.asset.AssetStates('Hors Service'), 'Hors Service'), (django_assets.assets.models.asset.AssetStates('Défectueux'), 'Défectueux'), (django_assets.assets.models.asset.AssetStates('Fonctionnel'), 'Fonctionnel')], default='OK', max_length=5, verbose_name='State'),
        ),
    ]
