# Generated by Django 2.0.6 on 2018-07-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180704_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.CharField(choices=[('REPA', 'En réparation'), ('INUSE', "En cours d'utilisation"), ('HS', 'Hors Service'), ('DFCT', 'Défectueux'), ('OK', 'Fonctionnel')], default='OK', max_length=5, verbose_name='State'),
        ),
    ]
